spring:
  application:
    name: hjelpemiddel-api

  datasource:
    username: ${OEBS_DB_USERNAME}
    password:  ${OEBS_DB_PASSWORD}
    url: ${ORACLE_URL}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.OracleDialect
  jackson:
    mapper:
      sort-properties-alphabetically: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    url: /openapi/hjelpemidler/openapi.yaml

server: #Det er denne som gir en server for tjenesten
  servlet:
    context-path: /api/v1

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

no.nav.security.jwt:
  issuer:
    azure:
      accepted_audience: ${AZURE_APP_CLIENT_ID}
      discoveryurl:  ${AZURE_APP_WELL_KNOWN_URL}

  #todo: Skal disse med?
  #management.endpoints.web.exposure.include=health,prometheus
  #management.endpoint.prometheus.access=unrestricted